apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "stakater-cloud-docs-v2.labels.stakater" . | indent 4 }}
{{ include "stakater-cloud-docs-v2.labels.chart" . | indent 4 }}
  name: {{ template "stakater-cloud-docs-v2.name" . }}
{{ if .Values.stakaterclouddocs-v2.deployment.annotations }}
  annotations:
{{ toYaml .Values.stakaterclouddocs-v2.deployment.annotations | indent 4 }}
{{ end }}
spec:
  replicas: {{ .Values.stakaterclouddocs-v2.deployment.replicas }}
  template:
    metadata:
      labels:
{{ toYaml .Values.stakaterclouddocs-v2.deployment.podLabels | indent 8 }}
    spec:
      {{- if .Values.stakaterclouddocs-v2.deployment.tolerations }}
      tolerations:
{{ toYaml .Values.stakaterclouddocs-v2.deployment.tolerations | indent 8 -}}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.stakaterclouddocs-v2.deployment.imagePullSecrets }}
      containers:
      - name: {{ .Values.stakaterclouddocs-v2.deployment.containerName }}
        image: "{{ .Values.stakaterclouddocs-v2.deployment.image.name }}:{{ .Values.stakaterclouddocs-v2.deployment.image.tag }}"
        ports:
        - containerPort: 8080
