kind: Service
apiVersion: v1
metadata:
  labels:
{{ include "stakater-cloud-docs-v2.labels.stakater" . | indent 4 }}
{{ include "stakater-cloud-docs-v2.labels.chart" . | indent 4 }}
    expose: {{ .Values.stakaterclouddocs-v2.service.labels.expose | quote }}
  name: {{ .Values.stakaterclouddocs-v2.service.name | quote }}
{{ if .Values.stakaterclouddocs-v2.service.annotations }}
  annotations:
{{ toYaml .Values.stakaterclouddocs-v2.service.annotations | indent 4 }}
{{ end }}
spec:
  selector:
{{ toYaml .Values.stakaterclouddocs-v2.deployment.podLabels | indent 4 }}
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
